version: "3.3"
services: 
  web:
    container_name: webnode
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3001:3001"
      - "3000:3000"
    volumes: 
      - "./workdir:/root/"
    tty: true
    links:
      - db
    networks:
      - backend
  db:
    container_name: dbmongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./database:/data/db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cafe
      ME_CONFIG_MONGODB_ADMINPASSWORD: cafeina123
    networks:
      - backend

networks:
  backend:
    driver: bridge
